<template>
  <div id="story">
    <v-container>
      <v-row justify-center>
          <v-col align-left cols="12" md="3" class="d-flex flex-column align-center mt-6 mt-md-16 order-2">
            <v-avatar center size="200">
              <v-img :src="story.authorPhoto"></v-img>
            </v-avatar>
            <div class="my-5">
            <h2>{{ story.author }}</h2>
            <span v-html="story.authorIntro" class="grey--text text--darken-1"></span>
            </div>
            <div class="justify-center">
              <v-btn color="yellow darken-2" class="white--text mr-4">Follow</v-btn>
              <v-btn outlined color="yellow darken-2" class="mr-4">Message</v-btn>
            </div>
          </v-col>
          <v-col align-right cols="12" md="9" class="ma-auto mt-16 order-1">
            <v-img :src="story.photo"></v-img>
            <h1 class="mt-6 mb-3">{{ story.title }}</h1>
            <span v-html="story.content"></span>
            <v-img :src="story.photoSecond"></v-img>
            <span v-html="story.contentSecond"></span>
          </v-col>
      </v-row>
    </v-container>
</div>
</template>
<script>
export default {
  name: 'Story',
  components: {
  },
  data () {
    return {
      stories: [
        {
          id: 1,
          photo: 'https://storage.googleapis.com/crossing-cms-cwg-tw/article/202006/article-5eed704f8313d.jpg',
          title: 'Why I left my job at McKinsey',
          author: 'Stephen Turban',
          authorPhoto: 'https://cw1.tw/CW/crossing/images/article/201801/writer-thumbnail-5a5da119186f5.jpg',
          authorIntro: '<p>Stephen Turban is a recent graduate of Harvard College and an alumnus of Jianguo Municipal Highschool. In high school, Stephen lived in Taipei as an exchange student; ever since, he has been writing about his time in Taipei, his experience\'s learning Mandarin, and his interest in organizations. Stephen\'s work has appeared in the Harvard Business Review, Slate, and has been cited by Hillary Clinton in speeches. Stephen currently works for McKinsey & Company where he tries to combine data science with questions about human and organizational behavior. In his free time, Stephen studies languages. Stephen is fluent in Mandarin and Spanish and is currently studying Vietnamese.</p>',
          content: ' <p>This past month, I made a big jump. I decided to leave my job at McKinsey and begin a new journey in Vietnam. I’m joining a team founding a new university in Saigon — Fulbright University Vietnam. It’s the nation’s first non-profit, private, liberal arts university.<p><p>Professor Datar and I sat at his office laughing. His laugh bellowed rhythmically from his chest — sounding something between a jolly pirate and an Indian Santa. My laugh screeched out of my throat — sounding somewhere between a hyena attack and a choking howler monkey.</p><p>Our laughs slowly began to fade until, finally, Professor Datar turned to me. “Enough, enough jokes” he finally got out, “let me think about your question.”<p>He paused stroking his enviably-full mustache. “Should Stephen do a PhD directly after senior year?” He asked himself aloud.</p><p>It was the fall of my senior year, and I was talking to professor Srikant Datar, a professor I admired at HBS (Harvard Business School) and introduced to me by my late-mentor David Garvin. I was deciding whether to apply directly to a PhD at a business school. So, I’d come to Srikant for some advice.</p><p>His advice changed my next three years and is the reason I recently left my job at McKinsey.</p><p>“If you want to be a professor who answers academic questions,” he said, “then you could always do a PhD directly.” He paused for a moment as if trying to figure out how to word his next sentence. “But, if you want to be a professor that answers the *big* questions that businesses care about, then I think you should work first.”</p><p>His advice was simple. If I wanted to research organizations, then I should work for a few years and witness real questions these organizations faced.</p><p>After Datar and my conversation, I went back to a library to think. It was there that I started the fragments of a plan for post-graduation. Though I’d be lying if I said the idea came all at once, over time the structure of my post-graduation became clear.</p>',
          photoSecond: 'https://storage.googleapis.com/crossing-cms-cwg-tw/ckeditor/202006/ckeditor-5eed6fe458d03.jpg',
          contentSecond: '<p>I decided to create a “real life degree” for myself before applying to a PhD: two semesters of real-life learning over three to four years. Each semester would be 1.5–2 years and would focus on a different type of business.</p><p>In my first “semester” after graduation, I decided I would focus on large, international organizations. The bigger and more international the better. That’s one of the main reasons I joined McKinsey.</p><p>In my second “semester,” I’d work with small and starting-up organizations. Ideally, in a place with few resources — like a quickly developing country. In both hoped I would learn different things — questions that were unique to big and small organizations.</p><p>A few months ago, I realized I was nearing the end of my first semester. I’d spent nearly two years with McKinsey across the US and China. And though I loved my time with McKinsey, I knew that there was a series of questions that I couldn’t answer at such a large and well-established firm.</p><p>About a month ago, my most recent project with McKinsey ended. So, I decided that it was time to move on to my next semester. After considerable thought, deliberation, and at least one conversation in a Tokyo karaoke salon with the song “Call Me Maybe” in the background, I decided to give my final notice to my manager.</p><p>Reflecting on my “first semester” briefly, I probably earned a C+ when it came to performance as a junior-level analyst. But, in terms of learning about large organizations, I think I got an A. I learned what it meant to be inspired at work by a manager, to be frustrated by internal politics, and how organizations desperately have to learn to stay relevant.</p><br<p>Now, my second semester has just begun, and I can’t be more excited. Naturally, if I were you, I would ask the question “So, what’s next Stephen?”</p<p>The answer is that there are a few different things that I’ll be doing.</p><p>The first, and most important, will be my work with Fulbright University. Fulbright University is Vietnam’s first ever private, not-for-profit, liberal arts university. It is born from a teaching program that Harvard administered for 20 years in Vietnam, named after anti-war Senator Fulbright, and made possible by sizable donations by the US & Vietnamese government.</p><p>It’s also a start-up — and that’s where I come in. My job over the next year+ will be to help create a center for entrepreneurship & innovation (like Harvard’s Ilab) and help fundraise to make the university sustainable. That also means I’ll be living full-time in Ho Chi Minh City, the economic capital of Vietnam.</p>'
        },
        {
          id: 2,
          photo: 'https://storage.googleapis.com/crossing-cms-cwg-tw/article/202006/article-5eee032a77a1b.jpg',
          title: 'Life lessons I have learnt from programming',
          author: 'Alice Yang',
          authorPhoto: 'https://cw1.tw/CW/images/blog/C1476841587912.jpg',
          authorIntro: '<p>Romantics who are hopelessly fascinated by storytelling. Their recent interests are virtual reality and meditation. Espresso and Greek yogurt are spiritual food for daily living. They don’t have pierced ears, but they like to appreciate beautiful earrings. When it\'s good, online auctions are the only antidote.With the blood of a natural reporter, I don\'t want to miss any novel things that happen in my life. I am determined to become a passionate code producer but always fail. Therefore, I decided to replace the code with words to record the whispers of generations.</p>',
          content: ' <p>This past month, I made a big jump. I decided to leave my job at McKinsey and begin a new journey in Vietnam. I’m joining a team founding a new university in Saigon — Fulbright University Vietnam. It’s the nation’s first non-profit, private, liberal arts university.<p><p>Professor Datar and I sat at his office laughing. His laugh bellowed rhythmically from his chest — sounding something between a jolly pirate and an Indian Santa. My laugh screeched out of my throat — sounding somewhere between a hyena attack and a choking howler monkey.</p><p>Our laughs slowly began to fade until, finally, Professor Datar turned to me. “Enough, enough jokes” he finally got out, “let me think about your question.”<p>He paused stroking his enviably-full mustache. “Should Stephen do a PhD directly after senior year?” He asked himself aloud.</p><p>It was the fall of my senior year, and I was talking to professor Srikant Datar, a professor I admired at HBS (Harvard Business School) and introduced to me by my late-mentor David Garvin. I was deciding whether to apply directly to a PhD at a business school. So, I’d come to Srikant for some advice.</p><p>His advice changed my next three years and is the reason I recently left my job at McKinsey.</p><p>“If you want to be a professor who answers academic questions,” he said, “then you could always do a PhD directly.” He paused for a moment as if trying to figure out how to word his next sentence. “But, if you want to be a professor that answers the *big* questions that businesses care about, then I think you should work first.”</p><p>His advice was simple. If I wanted to research organizations, then I should work for a few years and witness real questions these organizations faced.</p><p>After Datar and my conversation, I went back to a library to think. It was there that I started the fragments of a plan for post-graduation. Though I’d be lying if I said the idea came all at once, over time the structure of my post-graduation became clear.</p>',
          photoSecond: 'https://storage.googleapis.com/crossing-cms-cwg-tw/article/202006/article-5ee300223e99f.jpg',
          contentSecond: '<p>I decided to create a “real life degree” for myself before applying to a PhD: two semesters of real-life learning over three to four years. Each semester would be 1.5–2 years and would focus on a different type of business.</p><p>In my first “semester” after graduation, I decided I would focus on large, international organizations. The bigger and more international the better. That’s one of the main reasons I joined McKinsey.</p><p>In my second “semester,” I’d work with small and starting-up organizations. Ideally, in a place with few resources — like a quickly developing country. In both hoped I would learn different things — questions that were unique to big and small organizations.</p><p>A few months ago, I realized I was nearing the end of my first semester. I’d spent nearly two years with McKinsey across the US and China. And though I loved my time with McKinsey, I knew that there was a series of questions that I couldn’t answer at such a large and well-established firm.</p><p>About a month ago, my most recent project with McKinsey ended. So, I decided that it was time to move on to my next semester. After considerable thought, deliberation, and at least one conversation in a Tokyo karaoke salon with the song “Call Me Maybe” in the background, I decided to give my final notice to my manager.</p><p>Reflecting on my “first semester” briefly, I probably earned a C+ when it came to performance as a junior-level analyst. But, in terms of learning about large organizations, I think I got an A. I learned what it meant to be inspired at work by a manager, to be frustrated by internal politics, and how organizations desperately have to learn to stay relevant.</p><br<p>Now, my second semester has just begun, and I can’t be more excited. Naturally, if I were you, I would ask the question “So, what’s next Stephen?”</p<p>The answer is that there are a few different things that I’ll be doing.</p><p>The first, and most important, will be my work with Fulbright University. Fulbright University is Vietnam’s first ever private, not-for-profit, liberal arts university. It is born from a teaching program that Harvard administered for 20 years in Vietnam, named after anti-war Senator Fulbright, and made possible by sizable donations by the US & Vietnamese government.</p><p>It’s also a start-up — and that’s where I come in. My job over the next year+ will be to help create a center for entrepreneurship & innovation (like Harvard’s Ilab) and help fundraise to make the university sustainable. That also means I’ll be living full-time in Ho Chi Minh City, the economic capital of Vietnam.</p>'
        },
        {
          id: 3,
          photo: 'https://picsum.photos/1170/722/?random=1',
          title: 'What It’s REALLY Like to Be a Disney Cast Member',
          author: 'Sierra Vieregge',
          authorPhoto: 'https://i.pravatar.cc/200?img=47',
          authorIntro: '<p>Romantics who are hopelessly fascinated by storytelling. Their recent interests are virtual reality and meditation. Espresso and Greek yogurt are spiritual food for daily living. They don’t have pierced ears, but they like to appreciate beautiful earrings. When it\'s good, online auctions are the only antidote.With the blood of a natural reporter, I don\'t want to miss any novel things that happen in my life. I am determined to become a passionate code producer but always fail. Therefore, I decided to replace the code with words to record the whispers of generations.</p>',
          content: ' <p>This past month, I made a big jump. I decided to leave my job at McKinsey and begin a new journey in Vietnam. I’m joining a team founding a new university in Saigon — Fulbright University Vietnam. It’s the nation’s first non-profit, private, liberal arts university.<p><p>Professor Datar and I sat at his office laughing. His laugh bellowed rhythmically from his chest — sounding something between a jolly pirate and an Indian Santa. My laugh screeched out of my throat — sounding somewhere between a hyena attack and a choking howler monkey.</p><p>Our laughs slowly began to fade until, finally, Professor Datar turned to me. “Enough, enough jokes” he finally got out, “let me think about your question.”<p>He paused stroking his enviably-full mustache. “Should Stephen do a PhD directly after senior year?” He asked himself aloud.</p><p>It was the fall of my senior year, and I was talking to professor Srikant Datar, a professor I admired at HBS (Harvard Business School) and introduced to me by my late-mentor David Garvin. I was deciding whether to apply directly to a PhD at a business school. So, I’d come to Srikant for some advice.</p><p>His advice changed my next three years and is the reason I recently left my job at McKinsey.</p><p>“If you want to be a professor who answers academic questions,” he said, “then you could always do a PhD directly.” He paused for a moment as if trying to figure out how to word his next sentence. “But, if you want to be a professor that answers the *big* questions that businesses care about, then I think you should work first.”</p><p>His advice was simple. If I wanted to research organizations, then I should work for a few years and witness real questions these organizations faced.</p><p>After Datar and my conversation, I went back to a library to think. It was there that I started the fragments of a plan for post-graduation. Though I’d be lying if I said the idea came all at once, over time the structure of my post-graduation became clear.</p>',
          photoSecond: 'https://allears.net/wp-content/uploads/archive/blogs/allearsteam/mickeys-not-so-scary-halloween-party-18-07-700x525.jpg',
          contentSecond: '<p>I decided to create a “real life degree” for myself before applying to a PhD: two semesters of real-life learning over three to four years. Each semester would be 1.5–2 years and would focus on a different type of business.</p><p>In my first “semester” after graduation, I decided I would focus on large, international organizations. The bigger and more international the better. That’s one of the main reasons I joined McKinsey.</p><p>In my second “semester,” I’d work with small and starting-up organizations. Ideally, in a place with few resources — like a quickly developing country. In both hoped I would learn different things — questions that were unique to big and small organizations.</p><p>A few months ago, I realized I was nearing the end of my first semester. I’d spent nearly two years with McKinsey across the US and China. And though I loved my time with McKinsey, I knew that there was a series of questions that I couldn’t answer at such a large and well-established firm.</p><p>About a month ago, my most recent project with McKinsey ended. So, I decided that it was time to move on to my next semester. After considerable thought, deliberation, and at least one conversation in a Tokyo karaoke salon with the song “Call Me Maybe” in the background, I decided to give my final notice to my manager.</p><p>Reflecting on my “first semester” briefly, I probably earned a C+ when it came to performance as a junior-level analyst. But, in terms of learning about large organizations, I think I got an A. I learned what it meant to be inspired at work by a manager, to be frustrated by internal politics, and how organizations desperately have to learn to stay relevant.</p><br<p>Now, my second semester has just begun, and I can’t be more excited. Naturally, if I were you, I would ask the question “So, what’s next Stephen?”</p<p>The answer is that there are a few different things that I’ll be doing.</p><p>The first, and most important, will be my work with Fulbright University. Fulbright University is Vietnam’s first ever private, not-for-profit, liberal arts university. It is born from a teaching program that Harvard administered for 20 years in Vietnam, named after anti-war Senator Fulbright, and made possible by sizable donations by the US & Vietnamese government.</p><p>It’s also a start-up — and that’s where I come in. My job over the next year+ will be to help create a center for entrepreneurship & innovation (like Harvard’s Ilab) and help fundraise to make the university sustainable. That also means I’ll be living full-time in Ho Chi Minh City, the economic capital of Vietnam.</p>'
        },
        {
          id: 4,
          photo: 'https://picsum.photos/1170/722/?random=2',
          title: 'These women entrepreneurs started an edtech platform to enable peer learning',
          author: 'Tenzin Norzom',
          authorPhoto: 'https://i.pravatar.cc/200?img=5',
          authorIntro: '<p>Romantics who are hopelessly fascinated by storytelling. Their recent interests are virtual reality and meditation. Espresso and Greek yogurt are spiritual food for daily living. They don’t have pierced ears, but they like to appreciate beautiful earrings. When it\'s good, online auctions are the only antidote.With the blood of a natural reporter, I don\'t want to miss any novel things that happen in my life. I am determined to become a passionate code producer but always fail. Therefore, I decided to replace the code with words to record the whispers of generations.</p>',
          content: ' <p>This past month, I made a big jump. I decided to leave my job at McKinsey and begin a new journey in Vietnam. I’m joining a team founding a new university in Saigon — Fulbright University Vietnam. It’s the nation’s first non-profit, private, liberal arts university.<p><p>Professor Datar and I sat at his office laughing. His laugh bellowed rhythmically from his chest — sounding something between a jolly pirate and an Indian Santa. My laugh screeched out of my throat — sounding somewhere between a hyena attack and a choking howler monkey.</p><p>Our laughs slowly began to fade until, finally, Professor Datar turned to me. “Enough, enough jokes” he finally got out, “let me think about your question.”<p>He paused stroking his enviably-full mustache. “Should Stephen do a PhD directly after senior year?” He asked himself aloud.</p><p>It was the fall of my senior year, and I was talking to professor Srikant Datar, a professor I admired at HBS (Harvard Business School) and introduced to me by my late-mentor David Garvin. I was deciding whether to apply directly to a PhD at a business school. So, I’d come to Srikant for some advice.</p><p>His advice changed my next three years and is the reason I recently left my job at McKinsey.</p><p>“If you want to be a professor who answers academic questions,” he said, “then you could always do a PhD directly.” He paused for a moment as if trying to figure out how to word his next sentence. “But, if you want to be a professor that answers the *big* questions that businesses care about, then I think you should work first.”</p><p>His advice was simple. If I wanted to research organizations, then I should work for a few years and witness real questions these organizations faced.</p><p>After Datar and my conversation, I went back to a library to think. It was there that I started the fragments of a plan for post-graduation. Though I’d be lying if I said the idea came all at once, over time the structure of my post-graduation became clear.</p>',
          photoSecond: 'https://picsum.photos/1170/722/?random=3',
          contentSecond: '<p>I decided to create a “real life degree” for myself before applying to a PhD: two semesters of real-life learning over three to four years. Each semester would be 1.5–2 years and would focus on a different type of business.</p><p>In my first “semester” after graduation, I decided I would focus on large, international organizations. The bigger and more international the better. That’s one of the main reasons I joined McKinsey.</p><p>In my second “semester,” I’d work with small and starting-up organizations. Ideally, in a place with few resources — like a quickly developing country. In both hoped I would learn different things — questions that were unique to big and small organizations.</p><p>A few months ago, I realized I was nearing the end of my first semester. I’d spent nearly two years with McKinsey across the US and China. And though I loved my time with McKinsey, I knew that there was a series of questions that I couldn’t answer at such a large and well-established firm.</p><p>About a month ago, my most recent project with McKinsey ended. So, I decided that it was time to move on to my next semester. After considerable thought, deliberation, and at least one conversation in a Tokyo karaoke salon with the song “Call Me Maybe” in the background, I decided to give my final notice to my manager.</p><p>Reflecting on my “first semester” briefly, I probably earned a C+ when it came to performance as a junior-level analyst. But, in terms of learning about large organizations, I think I got an A. I learned what it meant to be inspired at work by a manager, to be frustrated by internal politics, and how organizations desperately have to learn to stay relevant.</p><br<p>Now, my second semester has just begun, and I can’t be more excited. Naturally, if I were you, I would ask the question “So, what’s next Stephen?”</p<p>The answer is that there are a few different things that I’ll be doing.</p><p>The first, and most important, will be my work with Fulbright University. Fulbright University is Vietnam’s first ever private, not-for-profit, liberal arts university. It is born from a teaching program that Harvard administered for 20 years in Vietnam, named after anti-war Senator Fulbright, and made possible by sizable donations by the US & Vietnamese government.</p><p>It’s also a start-up — and that’s where I come in. My job over the next year+ will be to help create a center for entrepreneurship & innovation (like Harvard’s Ilab) and help fundraise to make the university sustainable. That also means I’ll be living full-time in Ho Chi Minh City, the economic capital of Vietnam.</p>'
        }
      ]
    }
  },
  methods: {

  },
  computed: {
    id () {
      return parseInt(this.$route.params.id)
    },
    story () {
      return this.stories.filter(s => {
        return s.id === this.id
      })[0]
    }
  },
  mounted () {

  }
}

</script>

<style lang="stylus">
#story
  font-family 'Noto Sans TC', sans-serif
</style>
